import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import fs from "node:fs";
import path from "node:path";

function buildFirebaseMessagingSw(env: Record<string, string>): string {
  const firebaseConfig = {
    apiKey: env.VITE_FIREBASE_API_KEY || "",
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || "",
    projectId: env.VITE_FIREBASE_PROJECT_ID || "",
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
    appId: env.VITE_FIREBASE_APP_ID || "",
  };

  return `// Generated by Vite — do not edit manually
importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || "GoQuick";
  const body = payload.notification?.body || "";
  const data = payload.data || {};
  self.registration.showNotification(title, {
    body,
    icon: "/appicon.png",
    badge: "/appicon.png",
    data,
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const data = event.notification.data || {};
  let targetPath = "/notifications";
  if (data.errand_id) {
    targetPath = "/errands/" + data.errand_id;
  } else if (data.thread_id) {
    targetPath = "/chats/" + data.thread_id;
  }
  const url = new URL(targetPath, self.location.origin).href;
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.startsWith(self.location.origin) && "focus" in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    }),
  );
});
`;
}

function writeFirebaseMessagingSw(env: Record<string, string>): void {
  if (!env.VITE_FIREBASE_API_KEY) {
    return;
  }

  const outputPath = path.resolve(__dirname, "public/firebase-messaging-sw.js");
  fs.writeFileSync(outputPath, buildFirebaseMessagingSw(env), "utf8");
}

function firebaseMessagingSwPlugin(env: Record<string, string>): Plugin {
  return {
    name: "firebase-messaging-sw",
    buildStart() {
      writeFirebaseMessagingSw(env);
    },
    configureServer() {
      writeFirebaseMessagingSw(env);
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  writeFirebaseMessagingSw(env);

  return {
    plugins: [react(), firebaseMessagingSwPlugin(env)],
    server: {
      host: true,
      port: 5173,
      strictPort: true,
    },
  };
});
